# -*- coding: utf-8 -*-
"""LSTM_Numerical_Example_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tY6yRqqJlYm8DLUMhmMLAsT_rZzTsNo6
"""

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

# ── Weights (from PDF) ────────────────────────────────────────
#   Input weights    Hidden weights   Bias
Wf  = 0.5;  Whf = 0.1;  bf = 0.0    # Forget gate
Wi  = 0.6;  Whi = 0.2;  bi = 0.0    # Input gate
Wc  = 0.7;  Whc = 0.3;  bc = 0.0    # Candidate cell state
Wo  = 0.8;  Who = 0.4;  bo = 0.0    # Output gate

# ── Output layer (from PDF) ───────────────────────────────────
Wy  = 4.0;  by  = 0.0

# ── Initial states ────────────────────────────────────────────
h0 = 0.0    # h_0
C0 = 0.0    # C_0

# ── Input sequence ────────────────────────────────────────────
inputs = [1, 2, 3]    # X = [1, 2, 3]  →  predict x4

print("Parameters:")
print(f"  Wf={Wf}, Whf={Whf}, bf={bf}")
print(f"  Wi={Wi}, Whi={Whi}, bi={bi}")
print(f"  Wc={Wc}, Whc={Whc}, bc={bc}")
print(f"  Wo={Wo}, Who={Who}, bo={bo}")
print(f"  Wy={Wy}, by={by}")
print(f"  h_0={h0}, C_0={C0}")

# NOTE: The PDF rounds each gate value to 3 decimal places
# and carries the rounded value forward to the next step.
# We replicate that here so our results match the PDF exactly.

R = 3   # decimal places used in PDF

h = h0
C = C0

history = {'f':[], 'i':[], 'C_tilde':[], 'C':[], 'o':[], 'h':[]}

print("=" * 65)
print("        LSTM Forward Pass  —  Step by Step")
print("=" * 65)

for t, x_t in enumerate(inputs, start=1):

    print(f"\n{'─'*65}")
    print(f"  Time Step t={t}  |  x_t={x_t}  |  h_prev={h:.3f}  |  C_prev={C:.3f}")
    print(f"{'─'*65}")

    # 1. Forget Gate
    z_f = Wf*x_t + Whf*h + bf
    f_t = round(sigmoid(z_f), R)
    print(f"  1) Forget Gate:    f_{t} = σ({Wf}×{x_t} + {Whf}×{h:.3f} + {bf})"
          f" = σ({z_f:.3f}) ≈ {f_t:.3f}")

    # 2. Input Gate
    z_i = Wi*x_t + Whi*h + bi
    i_t = round(sigmoid(z_i), R)
    print(f"  2) Input Gate:     i_{t} = σ({Wi}×{x_t} + {Whi}×{h:.3f} + {bi})"
          f" = σ({z_i:.3f}) ≈ {i_t:.3f}")

    # 3. Candidate Cell State
    z_c = Wc*x_t + Whc*h + bc
    C_tilde = round(tanh(z_c), R)
    print(f"  3) Candidate:     C̃_{t} = tanh({Wc}×{x_t} + {Whc}×{h:.3f} + {bc})"
          f" = tanh({z_c:.3f}) ≈ {C_tilde:.3f}")

    # 4. Cell State Update
    C_new = round(f_t*C + i_t*C_tilde, R)
    print(f"  4) Cell State:     C_{t} = ({f_t:.3f}×{C:.3f}) + ({i_t:.3f}×{C_tilde:.3f})"
          f" ≈ {C_new:.3f}")
    C = C_new

    # 5. Output Gate
    z_o = Wo*x_t + Who*h + bo
    o_t = round(sigmoid(z_o), R)
    print(f"  5) Output Gate:    o_{t} = σ({Wo}×{x_t} + {Who}×{h:.3f} + {bo})"
          f" = σ({z_o:.3f}) ≈ {o_t:.3f}")

    # 6. Hidden State
    h = round(o_t * tanh(C), R)
    print(f"  6) Hidden State:   h_{t} = {o_t:.3f} × tanh({C:.3f}) ≈ {h:.3f}")

    history['f'].append(f_t)
    history['i'].append(i_t)
    history['C_tilde'].append(C_tilde)
    history['C'].append(C)
    history['o'].append(o_t)
    history['h'].append(h)

print(f"\n{'=' * 65}")

x4 = 4
print(f"  Time Step t=4  |  x_t={x4}  |  h_prev={h:.3f}  |  C_prev={C:.3f}")
print()

f4  = round(sigmoid(Wf*x4 + Whf*h + bf), R)
i4  = round(sigmoid(Wi*x4 + Whi*h + bi), R)
Ct4 = round(tanh(Wc*x4 + Whc*h + bc), R)
C4  = round(f4*C + i4*Ct4, R)
o4  = round(sigmoid(Wo*x4 + Who*h + bo), R)
h4  = round(o4 * tanh(C4), R)

print(f"  1) Forget Gate:    f_4  = {f4:.3f}   (PDF: 0.889)")
print(f"  2) Input Gate:     i_4  = {i4:.3f}   (PDF: 0.926)")
print(f"  3) Candidate:     C̃_4  = {Ct4:.3f}   (PDF: 0.990)")
print(f"  4) Cell State:     C_4  = {C4:.3f}   (PDF: 2.390)")
print(f"  5) Output Gate:    o_4  = {o4:.3f}   (PDF: 0.965)")
print(f"  6) Hidden State:   h_4  = {h4:.3f}   (PDF: 0.949)")

y_hat = Wy * h4 + by

print("=" * 45)
print("          FINAL PREDICTION")
print("=" * 45)
print(f"  h_4     = {h4:.3f}")
print(f"  W_y     = {Wy}")
print(f"  b_y     = {by}")
print(f"  y_hat   = {Wy} × {h4:.3f} + {by} = {y_hat:.3f}")
print("─" * 45)
print(f"  LSTM predicts  ≈  {y_hat:.1f}")
print(f"  PDF answer        3.8  ✓")
print(f"  This is close to 4 — the model")
print(f"  has learned the sequence pattern.")
print("=" * 45)

pdf_vals = [
    (0.622, 0.645, 0.604, 0.390, 0.690, 0.257),
    (0.736, 0.777, 0.899, 0.985, 0.808, 0.611),
    (0.827, 0.867, 0.974, 1.659, 0.904, 0.841),
]

header = f"{'t':>3} {'x_t':>5} {'f_t':>8} {'i_t':>8} {'C̃_t':>8} {'C_t':>8} {'o_t':>8} {'h_t':>8}"
print(header)
print("-" * 62)

keys = ['f','i','C_tilde','C','o','h']
for idx, x_t in enumerate(inputs):
    row = " ".join(f"{history[k][idx]:>8.3f}" for k in keys)
    print(f"  {idx+1}     {x_t}  {row}")

print("-" * 62)
print()
print("PDF expected values:")
print("-" * 62)
for idx, (x_t, pv) in enumerate(zip(inputs, pdf_vals)):
    row = " ".join(f"{v:>8.3f}" for v in pv)
    print(f"  {idx+1}     {x_t}  {row}")

print("-" * 62)
print(f"\n  Final Prediction  y_hat = {y_hat:.3f}   (PDF = 3.796)  ✓")

